title: "Edulíticas | Analítica del Aprendizaje – escrito por Daniel Amo Filvà (@danielamof)"
description: "Todo el contenido de eduliticas.com disponible en un único PDF"
author: "Daniel Amo Filvà"
url: "https://eduliticas.com"
baseurl: "" 

theme: minima

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      permalink: "/"
      title: "Edulíticas en reposo"
      content: |
        Ha llegado el momento de poner el proyecto **eduliticas.com** en reposo.  
        Todo el contenido del blog se ha comprimido en un único archivo PDF,  
        que puedes descargar en el siguiente enlace:

        [📥 Descargar todo el contenido de eduliticas.com](/Eduliticas_Un_espacio_sobre_analitica_del_aprendizaje_compressed.pdf)
